import { Chakra_Petch } from "next/font/google";
import "./globals.css";

// components
import Header from "@/components/Header";

const chakra = Chakra_Petch({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-chakra"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${chakra.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
